### PR TITLE
fix incorrect hashrate display on pool

### PR DESCRIPTION
**Pull request by ocminer**
set correct difficulty divider

### CODE REVIEW

**Comment by ocminer** [comment]
fixed

**Comment by moha83** [comment]
can you please share the exe file for windows 64 bit ;)

**Comment by staffnsnake** [comment]
https://github.com/todd1251/ccminer-x16r/releases/tag/2.2.4-x16r




Typos accidental. Please disregard meaningless expressions.







On Fri, Jan 19, 2018 at 10:51 AM +1100, "moha83" <notifications@github.com> wrote:












can you please share the exe file for windows 64 bit ;)

**Comment by moha83** [comment]
Thanks. But thi version runs with some errors it is not stable.
I'm looking for a build with ocminer correction

**Comment by todd1251** [comment]
@moha83 just add `-f 256` to the command line as per @Ondalf's comment.

@ocminer Thanks for fixing this! Later this weekend I will work on getting another build done but the tip from @Ondalf means folks can work around this easily.

**Pull request merged**
